// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnM6wmF7v9w-zvY6ucr15RW3aN1dYPM6o',
    appId: '1:259162808737:web:db128c12ec3504253a6be0',
    messagingSenderId: '259162808737',
    projectId: 'basanal-firebase-auth',
    authDomain: 'basanal-firebase-auth.firebaseapp.com',
    storageBucket: 'basanal-firebase-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP4lzDctx8T6hVtV4UULC0rPO5t3glDIc',
    appId: '1:259162808737:android:68d55071208df5433a6be0',
    messagingSenderId: '259162808737',
    projectId: 'basanal-firebase-auth',
    storageBucket: 'basanal-firebase-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkvlorAhrK9i39gh_TH-PYzPBiSeXKEI',
    appId: '1:259162808737:ios:eaa03ef678ba01713a6be0',
    messagingSenderId: '259162808737',
    projectId: 'basanal-firebase-auth',
    storageBucket: 'basanal-firebase-auth.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );

}